#role-binding.yaml

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ivanov-rb
subjects:
- kind: User
  name: ivanov
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ivanov-role
  apiGroup: rbac.authorization.k8s.io